name: CI
on:
  push:
    branches:
      - master-censys

# Cancel in-progress runs in current workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup docker qemu"
        uses: docker/setup-qemu-action@v3
      - name: "Setup docker buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build and push image
        run: |
          VERSION=$(date -u +%Y.%-m%d.%-s)
          docker buildx build --platform linux/amd64 -t ghcr.io/censys/oathkeeper:$VERSION --progress=plain -f .docker/Dockerfile-build .
          docker push ghcr.io/censys/oathkeeper:$VERSION
